"""Compile every result table into outputs/RESULTS.md (auto-generated, numbers only)."""
from __future__ import annotations

import json

import numpy as np
import pandas as pd

from . import config as C
from .data import LABELS


def md(df: pd.DataFrame, floatfmt="{:.3f}", index=False) -> str:
    df = df.reset_index() if index else df
    cols = [str(c) for c in df.columns]

    def fmt(v):
        if isinstance(v, (float, np.floating)):
            if np.isnan(v):
                return "–"
            return f"{int(v):,}" if float(v).is_integer() and abs(v) >= 1000 else floatfmt.format(v)
        if isinstance(v, (int, np.integer)):
            return f"{v:,}"
        return str(v).replace("|", "/")
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    lines += ["| " + " | ".join(fmt(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join(lines)


def t(name):
    return pd.read_csv(C.TAB_DIR / name)


def j(name):
    return json.load(open(C.TAB_DIR / name))


def run(prep=None, rep=None):
    fm = t("table3_forecast_metrics.csv")
    ae = j("table4_autoencoder_metrics.json")
    hy = j("hybrid_summary.json")
    lstm = fm[(fm.model == "LSTM (this study)") & (fm.subset == "all test days")].iloc[0]
    comp = pd.DataFrame([
        ["Data", "1 electrical panel, Fluke 935 logger, ~50 days, 70,621 samples",
         f"{len(prep.sites):,} telecom sites, daily rectifier KPIs, {len(prep.dates)} days, "
         f"{int(prep.observed.sum()):,} observed site-days"],
        ["Raw / selected features", "32 → 11", "33 candidates → 11"],
        ["Forecast target", "Active Power AN Avg (W)", "Avg DC Load Power (kW, reported in W)"],
        ["Forecast MAE", "61.12 W", f"{lstm.MAE_W:.1f} W"],
        ["Forecast RMSE", "135.79 W", f"{lstm.RMSE_W:.1f} W"],
        ["Forecast MAPE", "0.97 %", f"{lstm['MAPE_%']:.2f} %"],
        ["Forecast R²", "0.9668", f"{lstm.R2:.4f} pooled / {lstm.median_site_R2:.3f} median per site"],
        ["Skill vs persistence", "not reported", f"{lstm.skill_vs_persistence:.3f}"],
        ["AE reconstruction MAE / MSE / RMSE / R²", "0.0264 / 0.0019 / 0.0432 / 0.9004",
         f"{ae['MAE']:.4f} / {ae['MSE']:.4f} / {ae['RMSE']:.4f} / {ae['R2']:.4f} (site-relative z units)"],
        ["AE threshold", "95th pct of KDE (training errors)", f"95th pct of KDE (held-out validation errors) = {ae['threshold']:.4f}"],
        ["Anomalies flagged", "930 of 70,621 (1.32 %)",
         f"AE {hy['A_a_site_days']:,} ({hy['A_a_rate']:.2%}); OR {hy['A_or_site_days']:,} ({hy['A_or_rate']:.2%}); "
         f"AND {hy['A_and_site_days']:,} ({hy['A_and_rate']:.2%}) of test site-days"],
        ["Dominant root-cause indicators", "THD A, THD V",
         "conversion ratio, DC bus voltage, load swing, battery discharge (DC-plant supply quality)"],
        ["Detection validated", "no labels",
         "fault injection (OR recall 84 %) and operational events (AND 32x enriched for mains outages)"],
    ], columns=["Aspect", "Metry et al. (paper)", "This study"])

    out = ["# Results digest (auto-generated by `run_study.py report`)\n",
           "Narrative and interpretation: see `REPORT.md`.\n",
           "## Paper vs this study\n", md(comp),
           "\n## Preprocessing log\n", md(t("preprocessing_log.csv")),
           "\n## Placeholder replacement\n", md(t("placeholder_replacement.csv")),
           "\n## Fleet overview (modelled sites)\n", md(t("fleet_overview.csv"), "{:.2f}"),
           "\n## Table I — correlation observations and feature selection\n", md(t("table1_feature_selection.csv")),
           "\n## Outlier screening (consensus = box-plot ∧ KDE)\n",
           md(t("outlier_screening.csv").assign(feature=lambda d: d.feature.map(LABELS)), "{:.4f}"),
           "\n## Data partition\n", md(t("partition_summary.csv"), "{:.4f}"),
           "\n## Table III — forecasting metrics (test period, day-ahead)\n", md(fm, "{:.4f}"),
           "\n## Forecast error by lead time\n", md(t("forecast_horizon_mae.csv"), "{:.2f}"),
           "\n## Forecasting by site group (all test days)\n", md(t("forecast_by_group.csv"), "{:.4f}"),
           "\n## Table IV — LSTM autoencoder\n", md(pd.DataFrame([ae]).T.reset_index().rename(
               columns={"index": "metric", 0: "value"}), "{:.4f}"),
           "\n## Hybrid decision summary\n", md(pd.DataFrame([hy]).T.reset_index().rename(
               columns={"index": "quantity", 0: "value"}), "{:.4f}"),
           "\n## Root-cause indicator rates (share of site-days)\n", md(t("root_cause_rates.csv"), "{:.3f}"),
           "\n## Indicator elevation on flagged days (mean |z|)\n", md(t("indicator_elevation.csv").drop(columns="feature"), "{:.2f}"),
           "\n## Autoencoder feature contribution on flagged days\n", md(t("ae_feature_contribution.csv"), "{:.3f}"),
           "\n## Top diagnostic episodes (by severity)\n", md(t("diagnostic_episodes.csv").head(20), "{:.2f}"),
           ]
    for name, title in [("ablation/site_normalised_forecast_metrics.csv",
                         "Ablation — forecaster without window-level normalisation"),
                        ("forecast_window_sensitivity.csv", "Look-back window sensitivity (10 epochs each)"),
                        ("injection_recall.csv", "Synthetic fault injection — detection rate"),
                        ("injection_false_alarm.csv", "Synthetic fault injection — flag rate on unaffected days"),
                        ("threshold_sensitivity.csv", "Threshold percentile vs recall and alarm volume"),
                        ("weak_label_validation.csv", "Operational events as weak labels")]:
        if (C.TAB_DIR / name).exists():
            out += [f"\n## {title}\n", md(t(name), "{:.3f}")]
    if (C.TAB_DIR / "forecast_validation_comparison.json").exists():
        v = j("forecast_validation_comparison.json")
        vt = pd.DataFrame({k: v[k] for k in ("val_mse_all_h", "val_mse_h1")})
        out += ["\n## Validation-period comparison (window-relative MSE)\n", md(vt, "{:.3f}", index=True)]
    (C.OUT_DIR / "RESULTS.md").write_text("\n".join(out) + "\n")
    print(f"[report] {C.OUT_DIR / 'RESULTS.md'}")
